name: commitlint
on:
  pull_request:
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@60f406d294c519c95a6e9a3f6891faa9ef0e3860 # v1.0.5
